### ISSUE TITLE
NoMethodError: undefined method `find_all' for nil:NilClass

### ISSUE THREAD

**Issue by miah** [hw-labs/batali#10]
bundle exec batali resolve
    [Batali]: Loading sources... complete!
    ERROR: NoMethodError: undefined method `find_all' for nil:NilClass

**Comment by luckymike** [comment]
Hey Miah, can you share your Batali file?

**Comment by chrisroberts** [comment]
You can get the stacktrace dumped out using the `DEBUG=true` environment variable:

`DEBUG=true bundle exec batali resolve`

**Comment by miah** [comment]
Oh, nice I will try that one =)

**Comment by miah** [comment]
digging in.. https://gist.github.com/miah/4e9727626940642fa2ac

**Comment by chrisroberts** [comment]
Right on! Let me dig through this a bit. I have an update pushed into `develop` on [grimoire](https://github.com/spox/grimoire) that will kick back when the unit bucket is empty and provide the name of the missing unit (cookbook). That will likely help track it a bit better.

**Comment by chrisroberts** [comment]
Will kick out exception with useful message when this state is encountered (empty unit bucket) instead of just assuming it has units.

Thanks!
