### ISSUE TITLE
Casing between Batali and batali.manifest

### ISSUE THREAD

**Issue by gregkare** [hw-labs/batali#30]
We're switching from Librarian-Chef to Batali, so far the only nitpick I have is with the naming of the files: `Batali` with an uppercase b and `batali.manifest` with a lowercase b.

Is there a reason I'm missing behind this?

Thanks :)

**Comment by chrisroberts** [comment]
Hi. I guess the biggest reason is that Batali isn't Librarian! Outside of that, it was just a personal preference when building the tool.

Cheers!
