### ISSUE TITLE
Git private repo error

### ISSUE THREAD

**Issue by phoolish** [hw-labs/batali#37]
Is there additional configuration necessary to resolve private git repositories?

Batali file:
```
Batali.define do
  source 'https://supermarket.chef.io'
  cookbook 'repo', git: 'git://github.com/org/repo.git'
end
```

Output from batali resolve:
```
[ERROR]: Reason - git  clone '--' 'git://github.com/org/repo.git' '/Users/username/.batali/cache/git/Z2l0Oi8vZ2l0aHViLmNvbS90YWJsZXhpL2NoZWYtY29yZS5naXQ='  2>&1:Cloning into '/Users/username/.batali/cache/git/Z2l0Oi8vZ2l0aHViLmNvbS90YWJsZXhpL2NoZWYtY29yZS5naXQ='...
fatal: remote error: 
  Repository not found.
ERROR: Git::GitExecuteError: git  clone '--' 'git://github.com/org/repo.git' '/Users/username/.batali/cache/git/Z2l0Oi8vZ2l0aHViLmNvbS90YWJsZXhpL2NoZWYtY29yZS5naXQ='  2>&1:Cloning into '/Users/username/.batali/cache/git/Z2l0Oi8vZ2l0aHViLmNvbS90YWJsZXhpL2NoZWYtY29yZS5naXQ='...
fatal: remote error: 
  Repository not found.
```

**Comment by chrisroberts** [comment]
Hi! Private git repos will need a different syntax:

```ruby
cookbook 'repo', git: 'git@github.com:org/repo.git'
```
or
```ruby
cookbook 'repo', git: 'https://github.com/org/repo.git'
```

**Comment by phoolish** [comment]
Thanks for the fast response!

Hmm, it did resolve this time, but I had to enter a user/pass and requires generating a token (MFA enabled account) and reprompts for all dependencies.

Is there no way to use an ssh_key config or an ENV value?

**Comment by luckymike** [comment]
It's Ruby, so you should be able to do an ENV.fetch(key)

**Comment by phoolish** [comment]
@luckymike could elaborate?

**Comment by luckymike** [comment]
`ENV.fetch('foo')` will return the ENV variable 'foo', so you can use that within the config to return an ENV variable.

**Comment by phoolish** [comment]
Sorry, I should have been more specific.  I know how to return ENV var into a ruby file.  Do you then set the user/pass in the Batali file?

**Comment by phoolish** [comment]
@luckymike Went way of track of the original question.  I think I've sorted it out.  Thanks for the patience.
