### ISSUE TITLE
Defining path does not affect installed cookbook

### ISSUE THREAD

**Issue by luckymike** [hw-labs/batali#54]
Setting the `:path` flag in the Batali file correctly allows cookbook resolution for a cookbook that is not in the root directory of the repo, however, the installed artifact contains the full repo contents rather than just the cookbook, e.g.:

```
$ ls cookbooks/zncrypt-4.1.0
CONTRIBUTING  LICENSE  README.md  zncrypt

$ ls cookbooks/zncrypt-4.1.0/znycrpt
Berksfile  CONTRIBUTING  Gemfile  LICENSE  README.md  attributes  libraries    
metadata.rb  providers  recipes  resources  test
```

This is a problem because damaging files (roles, environments, etc.) could be included in the top level and installed accidentally via `knife upload cookbooks`

**Comment by chrisroberts** [comment]
Fixed as of 0.2.28
