### ISSUE TITLE
Add vendor option

### ISSUE THREAD

**Issue by apollocatlin** [hw-labs/batali#59]
A good berkshelf feature preventing me from starting to use bitali is the option to "vendor" the cookbooks and output them to a declared path.

I am specifically am looking to integrate this with our packer workflow where we run chef-solo in a vm, but resolve the cookbooks outside of the vm prior to bootstrapping then upload the cookbooks.

**Comment by chrisroberts** [comment]
Hi! This feature exists in batali as the `install` command. It accepts a `--path` option for the destination of the cookbooks to be installed. By default this is `./cookbooks` but can be modified via the `--path` option. For example, to install them to the vendor directory:

```
$ batali install --path vendor
```
or to a cookbooks subdirectory within vendor:

```
$ batali install --path vendor/cookbooks
```

Cheers!

**Comment by apollocatlin** [comment]
Awesome thanks man.
