### ISSUE TITLE
Resolve dependency tree with different cookbooks that share the same name

### ISSUE THREAD

**Issue by kenny-evitt** [hw-labs/batali#65]
This may be a contrived issue – I really only ran into it because I have two cookbooks, one of which was forked from the other, and I replaced one dependency in the first cookbook with a dependency on another cookbook *but with the same name*.

For *cookbook1*, I had problems with [the Supermarket *postgresql* cookbook](https://github.com/hw-cookbooks/postgresql) so I replaced it with [this cookbook](https://github.com/phlipper/chef-postgresql).

*cookbook2* still depends on [the Supermarket *postgresql* cookbook](https://github.com/hw-cookbooks/postgresql).

In my specific circumstances, this is a non-issue. But I can certainly imagine someone wanting to use both of the *postgresql* cookbooks.

Maybe this only makes sense for infrastructure mode.

**Comment by luckymike** [comment]
I don't think this is a contrived issue. We've discussed a similar use case internally. I think this is an enhancement we'll be adding in the near future.

**Comment by chrisroberts** [comment]
Hi! So, #69 allows for single cookbooks to have multiple sources. However, in #66 I discussed a little around why having multiple implementations under a common name is not a good run time situation and would highly caution against it in practice. That said, #69 covers what you're looking for and should be released shortly.

Cheers!

**Comment by chrisroberts** [comment]
Multiple source support for single cookbooks in infrastructure mode is available as of version 0.3.12. Thanks!

**Comment by kenny-evitt** [comment]
@chrisroberts Thanks!
