### ISSUE TITLE
Create Gitter room for this repo

### ISSUE THREAD

**Issue by kenny-evitt** [hw-labs/batali#67]
[Gitter](https://gitter.im) is very nice little chat app that integrates rooms directly with GitHub repos (and orgs). I've found it to be a nice alternative venue for users to share transient or ephemeral content (like this issue), particularly questions, instead of submitting GitHub issues.

**Comment by luckymike** [comment]
@kenny-evitt I've used gitter before, and while it's cool, my experience was that it's a lot of cognitive load (an entire additional chat app to attend to) for a single project's conversation. Feel free to open issues or visit us in #heavywater on Freenode in IRC. :)

Glad you're checking Batali out!

**Comment by kenny-evitt** [comment]
@luckymike Understood

I just have never found an IRC client that doesn't make channels or rooms *look* so needlessly busy.

**Comment by webframp** [comment]
@kenny-evitt https://www.irccloud.com is nice

**Comment by kenny-evitt** [comment]
@webframp That does look really nice; thanks for the link.
