### ISSUE TITLE
Complete restrict functionality

### ISSUE THREAD

**Issue by chrisroberts** [hw-labs/batali#7]

**Comment by chrisroberts** [comment]
Finish the `restrict` functionality within `Batali` file

**Comment by chrisroberts** [comment]
Restrictions can be loaded from the Batali file. @calebhailey made the suggestion of swapping the key from `:to` to `:source` making it a bit more explicit. We _could_ do both, but that's just introducing cruft. Since it's not even documented yet, I think I'll make the switch now and use it going forward.

**Comment by calebhailey** [comment]
\o/
