### ISSUE TITLE
[ERROR]: Reason - uninitialized constant Chef::REST

### ISSUE THREAD

**Issue by zhelyan** [hw-labs/batali#76]
Fails when `chef_server` is used in the Batali file, looks like `'chef/rest'` isn't explicitly required?

**Comment by chrisroberts** [comment]
Hi! Indeed, this was a breaking change that was introduced. I'll get a fix released shortly. Thanks for the report!

**Comment by chrisroberts** [comment]
Fix released in v0.4.4.

Thanks for the report!
