### ISSUE TITLE
no metadata error isn't verbose

### ISSUE THREAD

**Issue by miah** [hw-labs/batali#9]
bundle exec batali update -V
    [Batali]: Loading sources... error!
    [ERROR]: Reason - No such file or directory - No metadata file available to load!
    ERROR: Errno::ENOENT: No such file or directory - No metadata file available to load!

**Comment by chrisroberts** [comment]
Hi! I haven't added in much for debug-ish output, so kicking on the verbosity flag is currently a little useless. I'll run through and start dropping things in to get some better feedback.

**Comment by miah** [comment]
Ya, I manually modified my installed gem and just added '#{ path }' to the Error.

**Comment by chrisroberts** [comment]
Path is included in exception message (and more debug/verbose output has been added)

Thanks!
